name: bash_unit CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - uses: actions/checkout@v2

    - name: install Ubuntu dependencies with sudo apt install -y
      run: sudo apt install -y gawk curl jq npm pandoc

    - name: install NPM packages
      run: sudo npm install heml -g

    - name: Check for basic execution
      run: ./postmark check

    - name: Unit testing with bash_unit
      run: tests/bash_unit tests/test_*
